#!/bin/bash

# Oracle Cloud GPU VM Provisioning Guide
# Since OCI CLI setup is complex, this script provides exact parameters for web console

echo "🚀 Oracle Cloud GPU VM Provisioning Instructions"
echo "=================================================="
echo ""
echo "Since OCI CLI requires complex setup, use the Oracle Cloud Console:"
echo ""
echo "1. Go to: https://cloud.oracle.com"
echo "2. Navigate: Compute → Instances → Create Instance"
echo ""
echo "📋 EXACT CONFIGURATION (copy these values):"
echo ""
echo "Basic Information:"
echo "  Name: f1-gpu-vm"
echo "  Compartment: (use same as current VM)"
echo ""
echo "Image and Shape:"
echo "  Image: Oracle Linux 8"
echo "  Shape: Change Shape → Specialty and previous generation"
echo "         → VM.GPU.A10.1 (1 OCPU, 15 GB RAM, 1x NVIDIA A10)"
echo ""
echo "Networking:"
echo "  VCN: (same as current VM)"
echo "  Subnet: (same public subnet as current VM)"
echo "  Public IP: Assign a public IPv4 address"
echo ""
echo "SSH Keys:"
echo "  Upload: ~/.ssh/ssh-key-2025-07-01.key.pub"
echo ""
echo "Boot Volume:"
echo "  Size: 200 GB (for AI models)"
echo "  Performance: Balanced"
echo ""
echo "Advanced Options:"
echo "  Preemptible instance: YES (saves ~60% cost)"
echo "  Maximum duration: 24 hours (auto-recreate)"
echo ""
echo "💰 COST BREAKDOWN:"
echo "  VM.GPU.A10.1 Regular: ~$1.02/hour = $734/month"
echo "  VM.GPU.A10.1 Preemptible: ~$0.41/hour = $295/month ✅"
echo ""
echo "🔧 AFTER PROVISIONING:"
echo "  1. Note the new public IP address"
echo "  2. Update SSH connection: ssh -i ~/.ssh/ssh-key-2025-07-01.key opc@NEW_IP"
echo "  3. Run GPU setup script (will be created next)"
echo ""
echo "⚠️  IMPORTANT:"
echo "  - Preemptible instances can be terminated by Oracle with 30s notice"
echo "  - They automatically restart but you may lose in-progress work"
echo "  - Perfect for development/testing, less ideal for production"
echo ""
echo "Ready to provision? (y/n)"
read -r response
if [[ "$response" =~ ^[Yy]$ ]]; then
    echo ""
    echo "🌐 Opening Oracle Cloud Console..."
    open "https://cloud.oracle.com/compute/instances"
    echo ""
    echo "Follow the configuration above!"
    echo "Once provisioned, run: ./setup-gpu-vm.sh NEW_IP_ADDRESS"
else
    echo "Provisioning cancelled."
fi